version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  http_source:
    image: springcloudstream/http-source-kafka:latest
    container_name: http_source
    ports:
     - "9091:9091"
    depends_on:
     - broker
    environment:
      SERVER_PORT: 9091
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
      SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION: 'strings'
      HTTP_PATH-PATTERN: '/demo'

  # binfn:
  #   image: docker.io/library/binfn:0.0.1-SNAPSHOT
  #   container_name: binfn
  #   depends_on:
  #    - http_source
  #   environment:
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  ws_sink:
    image: springcloudstream/websocket-sink-kafka:latest
    container_name: ws-sink
    ports:
     - "9095:9095"
     - "9096:9096"
    depends_on:
     - broker, http_source
    environment:
      SERVER_PORT: 9096
      WEBSOCKET_CONSUMER_PORT: 9095
      WEBSOCKET_CONSUMER_PATH: '/ws'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
      SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION: 'binstrings'
      SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      ENDPOINTS.WEBSOCKETCONSUMERTRACE.ENABLED: true